### ISSUE TITLE
Run IR/SN app not in docker

### ISSUE THREAD

**Issue by carpawell** [nspcc-dev/neofs-dev-env#75]
Is there any way to run IR/SN app not in docker? This could make the testing process faster and make it more easier to run code with an attached debuger.

I see this as an optional feature when `docker-compose` starts: the whole network does `up` and it is possible to connect(register) local(not docker) go application as a SN to that network.

Maybe there must appear some configuration/script files for the correct app connection in that repository.

**Comment by alexvanin** [comment]
> Is there any way to run IR/SN app not in docker? 

Sure. All chain endpoints are available outside of the docker environment. You can launch neofs-dev-env and then run your neofs-node binary with config file, e.g. `./bin/neofs-node -config config.yml`. 

As you see you need correct config file with script hashes, endpoints, etc. After https://github.com/nspcc-dev/neofs-node/issues/493 there will be easier way to build your own config.yml from example. Right now it is a bit a mess of configuration values. However I don't think neofs-dev-env will contain yml configs for nodes, since ENVs are used by other applications.
